sudo: required
language: cpp

addons:
  apt:
    packages:
    - docker-ce

services:
- docker

before_install:
- docker pull hippobaro/asuswrt-musl-crosscompile

script:
- chmod +x build.sh
- "./build.sh"

deploy:
  provider: releases
  api_key:
    secure: J/uHXpCzDAwTlmv46U62RgVnky0b5Dx77C5JP8YcW/v8sA2Pg4Em9GNcx7r2lnfCsd2ZJDahwTxZzKD6FY2Kuy6znBCumk4F0ltpslcoSin4kt17qzUcd8+mZzRSCdZoh7X0kn9ALRiLuCJjYNuoE+UaYHSNZeX7njwW4fw/VSmiq5xMqJfaoqL+s9RvrCcpFPYIIVWnO4dtKmgV3OM5i5lcokM0DhQqEiQl7dAhZOtBZX2lG6XfsW0cz+kOu4zO+zlkdVXU6qQVtedtjr9LCLFq/pxi2csbGHCWoUzFOI2eHCzz3IlG6Wpxn2g7jlPLyyLqs6Fkx9qK4esfsvVbp7pd+gJ2YhQJHztsGhaT8cTpy326jksEbTtxdg98YxOzw467FRg+LwlmGomMYB85F4x08sCjl3kSfQd3f8VDYQXmirjHDY3V4ok7A9AqEEp9d6Fp6iOTSpNPp2tK2a5eFdiL1dXp4ulbQKg6BBM8hPrF5lbgsnkJG7+Ox1+wwYKRruL/geDCNhwVxsjj5G7s38uRxTRRpYfC0G6mEAgtkE2byiy/mm6xqfYjXXpvyiGzWkhErAJc5zGPdqGugJ1IVT9hfF1OR+v8mWQj0z1so5sgov1qBiSvsBALY49a8uDbiONJ4L8sJ6KoGIrIMqptoQdmPTalOLvt7cXwrOTwMdc=
  file: build/thunet_asus_keepalive
  skip_cleanup: true
  name: v.$(git log -1 --format=%ad --date=format:'%Y-%m-%d')-$(git describe --match=NeVeRmAtCh --always --dirty)
  body: "SHA1 : $(sha1sum build/thunet_asus_keepalive)"
  on:
    repo: HippoBaro/thunet_asus_keepalive
    tags: true
